version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-baeldung-bff
    ports:
      - 8080:8080
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      # KC_HOSTNAME_URL: http://localhost:7080/auth
      # KC_HOSTNAME_ADMIN_URL: http://localhost:7080/auth
      KC_HTTP_RELATIVE_PATH: /auth
      #KC_LOG_LEVEL: DEBUG