scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/baeldung
client-id: baeldung-bff
client-secret: w8DGbCb7LLWYPQVrnP8eVF4DxKeOhBok
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles
gateway-port: 7081
gateway-prefix: /gateway
resource-server-port: 7084
audience:

server:
  port: ${gateway-port}
  ssl:
    enabled: false

spring:
  cloud:
    gateway:
      default-filters:
      - TokenRelay=
      routes: 
        - id: gateway
          uri: ${scheme}://${hostname}:${resource-server-port}
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SaveSession
            - StripPrefix=1
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${issuer}
        registration:
          baeldung-bff:
            provider: keycloak
            authorization-grant-type: authorization_code
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope:
            - email
            - profile
            - roles 
            # openid,profile,email,roles
            # redirect-uri: ${issuer}/login/oauth2/code/keycloak

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer}
            authorities:
              - path: ${authorities-json-path}
            aud: ${audience}
        client:
          client-uri: ${reverse-proxy-uri}${gateway-prefix}
          security-matchers:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout
            - /auth
            - /**
          permit-all:
            - /api/**
            - /login/**
            - /oauth2/**
            - /auth
            - /**
          csrf: cookie-accessible-from-js
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
        # OAuth2 resource server configuration
        resourceserver:
          permit-all:
            - /error
            - /login-options
            - /v3/api-docs/**
            - /swagger-ui/**
            - /actuator/health/readiness
            - /actuator/health/liveness

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        boot: INFO
        security: INFO
        web: TRACE

---
spring:
  config:
    activate:
      on-profile: no-ssl
server:
  ssl:
    enabled: false
scheme: http
